from bot import GourmetGame
import asyncio
import os
from manual_testing import delete_databases, run, send_message, TEST_DATABASE_ADDRESS, TEST_LOG_ADDRESS, Message

if __name__ == "__main__":
    delete_databases()
    client = GourmetGame(TEST_DATABASE_ADDRESS, TEST_LOG_ADDRESS, run, send_message, silent_logging=True, testing=True)
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg chances")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg start")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg leaderboard")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg play")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg play")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg play")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg pull all")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg fish all")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg play")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg play")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg play")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg pull all")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg fish all")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg event personaltrainer")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg special asd")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg event pirates")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg event megalodon")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg pull all")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg adventure")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg finisher asd")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg pull all")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg leaderboard")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg fish all")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg event pirates")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg event megalodon")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg pull all")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg play")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg play")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg play")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg status")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg fish all")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg event personaltrainer")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg event personaltrainer")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg event personaltrainer")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg pull all")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg boss")))
    asyncio.run(client.on_message(Message("3", "Manual Tester", "!gg status")))
    delete_databases()
    
